### ISSUE TITLE
Updating dependencies failed when generating an app

### ISSUE THREAD

**Issue by alexiscz** [catarizea/generator-react-native-tvos#6]
Hello, 

I have tried to use your generator to bootstrap a quick prototype. By the way, great idea to make this generator. 
I get errors (and some dependencies warning :-)) at the end of your generator script. 
First in faker-data.js:41 then another in events.js:160 (maybe the 2nd one is linked to the first one ?)
My computer is running Node 6.4.0 on Mac OS Sierra. 

Do you have any idea ? 

Thanks,

Alexis

```

⠇ Updating dependencies
warning "react-native > metro > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".
warning " > react-native-fs@2.9.11" has incorrect peer dependency "react-native@^0.51.0".
warning " > react-native-fs@2.9.11" has incorrect peer dependency "prop-types@15.6.0".
warning " > react-native-fs@2.9.11" has unmet peer dependency "create-react-class@^15.6.2".
warning " > babel-jest@22.4.3" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
/Users/blank/Documents/GitHub/lab/tvos/RNFubizTV/scripts/faker-data.js:41
);
^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/faker-data
Directory: /Users/blank/Documents/GitHub/lab/tvos/RNFubizTV
Output:
".

✖ Updating dependencies
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'error' of undefined
    at installDeps.then.catch (/Users/blank/.nvm/versions/node/v6.4.0/lib/node_modules/generator-react-native-tvos/generators/app/utils/yarn.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by catarizea** [comment]
Try to use node version 8 to see if it is an environment related problem, first.

**Comment by alexiscz** [comment]
Indeed with node 8, there is no error in the generating script. I was able to go deeper but now I have an error with the Yarn script. 
Yarn was installed with brew. 

```
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/blank/Documents/GitHub/lab/tvos/RNFubizTV/backend/server.js:6:58)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c cd backend && node serve
```

**Comment by catarizea** [comment]
Are you using node 8 inside the terminal window for the backend server, also?

**Comment by alexiscz** [comment]
I have used NVM to install node 8 on my computer (I still need an older version of node for my everyday projects). 
All my commands are running in the same terminal window. (see below)
![capture d ecran 2018-04-13 a 11 21 13](https://user-images.githubusercontent.com/5859470/38727283-dcca4a92-3f0c-11e8-9666-063fd8f56f1a.png)

I have also tried to reinstall yarn using the brew's flag --without-node but I still have the same issue. 
Do you think I should stop using nvm and install Node 8 globally on my computer ? 
Or maybe this error comes from my dependencies warning .. 🤷‍♂️

**Comment by catarizea** [comment]
No, you shouldn't make node v8 the default one if you need older versions. Try to start the server like this form inside the same v8 terminal window `node backend/server`.

**Comment by alexiscz** [comment]
I am stupid... This command works!

**Comment by catarizea** [comment]
The right way is first `cd backend/` and then `node server`. You will need to also `yarn run start` from another v8 terminal window before running the app from Xcode. I'll modify the README to accommodate this use case. Thank you for your feedback!
